# This is a basic workflow to help you get started with Actions

name: build leaderboard image

# Controls when the workflow will run
on:
  schedule:
    # twice an hour
    - cron: "26,56 * * 12 *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.5.0

      # Runs a set of commands using the runners shell
      - name: Build leaderboard image
        env:
          AOC_TOKEN: ${{ secrets.AOC_TOKEN }}

        run: |
          cd leaderboard
          mkdir output
          npm install
          node index.js

      - name: upload leaderboard image to s3
        uses: prewk/s3-cp-action@v2
        with:
          aws_access_key_id: ${{ secrets.S3_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          source: "./leaderboard/output/full.png"
          dest: "s3://visionist-advent-of-code/leaderboard2021.png"
          flags: --acl public-read --cache-control no-cache
